// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airQuality.proto

package airQualityService;

public final class airQualityServiceImpl {
  private airQualityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airQuality_requestQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airQuality_requestQuality_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airQuality_responseByArea_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airQuality_responseByArea_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020airQuality.proto\022\nairQuality\"/\n\016reques" +
      "tQuality\022\017\n\007country\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\"" +
      "K\n\016responseByArea\022\014\n\004city\030\001 \001(\t\022\r\n\005index" +
      "\030\002 \001(\005\022\014\n\004band\030\003 \001(\t\022\016\n\006advice\030\004 \001(\t2h\n\021" +
      "airQualityService\022S\n\025requestQualityServi" +
      "ce\022\032.airQuality.requestQuality\032\032.airQual" +
      "ity.responseByArea\"\0000\001B,\n\021airQualityServ" +
      "iceB\025airQualityServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airQuality_requestQuality_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airQuality_requestQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airQuality_requestQuality_descriptor,
        new java.lang.String[] { "Country", "City", });
    internal_static_airQuality_responseByArea_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airQuality_responseByArea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airQuality_responseByArea_descriptor,
        new java.lang.String[] { "City", "Index", "Band", "Advice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
