// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQualityStream.proto

package CheckingQualityStreamService;

public interface streamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckingQualityStream.streamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
