// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AverageValue.proto

package AverageValue;

public final class AverageValueImpl {
  private AverageValueImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AverageValueImpl_AverageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AverageValueImpl_AverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AverageValueImpl_AverageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AverageValueImpl_AverageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AverageValue.proto\022\020AverageValueImpl\"!" +
      "\n\016AverageRequest\022\017\n\007request\030\001 \001(\005\"#\n\017Ave" +
      "rageResponse\022\020\n\010response\030\001 \001(\0022b\n\014Averag" +
      "eValue\022R\n\007Average\022 .AverageValueImpl.Ave" +
      "rageRequest\032!.AverageValueImpl.AverageRe" +
      "sponse\"\000(\001B\"\n\014AverageValueB\020AverageValue" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AverageValueImpl_AverageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AverageValueImpl_AverageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AverageValueImpl_AverageRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_AverageValueImpl_AverageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AverageValueImpl_AverageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AverageValueImpl_AverageResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
