// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AverageValue.proto

package AverageValue;

public interface AverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AverageValueImpl.AverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request = 1;</code>
   */
  int getRequest();
}
