// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AverageValue.proto

package AverageValue;

public interface AverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AverageValueImpl.AverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float response = 1;</code>
   */
  float getResponse();
}
