// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airQuality.proto

package airQualityService;

public interface requestQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airQuality.requestQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * setCountry(), getCountry()
   * </pre>
   *
   * <code>string country = 1;</code>
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * setCountry(), getCountry()
   * </pre>
   *
   * <code>string country = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
