// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQualityStream.proto

package CheckingQualityStreamService;

public final class CheckingQualityStreamServiceImpl {
  private CheckingQualityStreamServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckingQualityStream_streamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckingQualityStream_streamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckingQualityStream_streamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckingQualityStream_streamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CheckingQualityStream.proto\022\025CheckingQ" +
      "ualityStream\"\037\n\rstreamRequest\022\016\n\006sample\030" +
      "\001 \001(\005\"\"\n\016streamResponse\022\020\n\010response\030\001 \001(" +
      "\t2~\n\025CheckingQualityStream\022e\n\020Requesting" +
      "Stream\022$.CheckingQualityStream.streamReq" +
      "uest\032%.CheckingQualityStream.streamRespo" +
      "nse\"\000(\0010\001BB\n\034CheckingQualityStreamServic" +
      "eB CheckingQualityStreamServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckingQualityStream_streamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckingQualityStream_streamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckingQualityStream_streamRequest_descriptor,
        new java.lang.String[] { "Sample", });
    internal_static_CheckingQualityStream_streamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckingQualityStream_streamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckingQualityStream_streamResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
