// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQualityStream.proto

package CheckingQualityStreamService;

public interface streamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckingQualityStream.streamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sample = 1;</code>
   */
  int getSample();
}
