// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQuality.proto

package CheckingQuality;

public interface CheckingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckingQuality.CheckingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
