// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQuality.proto

package CheckingQuality;

public interface CheckingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckingQuality.CheckingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
