// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckingQuality.proto

package CheckingQuality;

public final class CheckingQualityImpl {
  private CheckingQualityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckingQuality_CheckingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckingQuality_CheckingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckingQuality_CheckingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckingQuality_CheckingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CheckingQuality.proto\022\017CheckingQuality" +
      "\"!\n\017CheckingRequest\022\016\n\006number\030\001 \001(\005\"$\n\020C" +
      "heckingResponse\022\020\n\010response\030\001 \001(\t2d\n\017Che" +
      "ckingQuality\022Q\n\010Checking\022 .CheckingQuali" +
      "ty.CheckingRequest\032!.CheckingQuality.Che" +
      "ckingResponse\"\000B(\n\017CheckingQualityB\023Chec" +
      "kingQualityImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckingQuality_CheckingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckingQuality_CheckingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckingQuality_CheckingRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_CheckingQuality_CheckingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckingQuality_CheckingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckingQuality_CheckingResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
